### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by robsel118** [ufz-vislab/VtkUnity#5]
I have build the project and added the .DLLs in the same folder as the .exe, but I stil get the DllNotFoundException warning. Do you know if there is another folder to put them in the newest version of Unity (2018.2) ?

**Comment by bilke** [comment]
This project is not maintained anymore and I can't tell you anything about Unity 2018.2, sorry.

**Comment by anranx** [comment]
@robsel118  Hi! Have you already solved the problem? I meet the same error. DllNotFoundException: Kitware.VTK.vtkCommon.Unmanaged.dll ,but when I check the Aseert/Plugins ,this dll is right there.
I am using Unity2018.4.0f1+ActiViz5.8. Thank you very much if you can answer me.

**Comment by robsel118** [comment]
@anranx I am sorry, I did not manage to solve it unfortunately
